export interface InstructionGuide {
  id: string
  title: string
  group: "Start here" | "Create environments" | "Connect and publish" | "Use and manage"
  steps: readonly string[]
  note?: string
}

// Keep these in the order a new user is most likely to need them. Reading
// progress is tracked by ID, so copy edits do not reset completed guides.
export const instructionGuides: readonly InstructionGuide[] = [
  { id: "settings", title: "Set up Yougori", group: "Start here", steps: ["Open Settings at the top of the main window.", "Choose whether Yougori launches when you sign in, keeps this PC awake while environments run, and starts selected environments automatically.", "Review the default storage location. For a new environment, choose its own drive in New environment."], note: "Moving the shared runtime folder requires exporting and removing existing environments first." },
  { id: "container", title: "Create a container", group: "Create environments", steps: ["Select New environment → Container.", "Name it and choose an OCI image, such as nginx or ubuntu. Set CPU, memory, storage, ports, and an optional startup command.", "Press Create environment. Watch the new node for preparation progress, then press Start or Open."], note: "Images may need to download the first time. Your container files persist across normal stops." },
  { id: "gpu", title: "Create a GPU container", group: "Create environments", steps: ["Select New environment → Container, then turn on GPU access.", "Check the NVIDIA CUDA setup shown in the form and complete it if needed.", "Choose a compatible OCI image and your resource values, then create the environment. Start it from its node."], note: "Requires a supported NVIDIA GPU, Windows driver, and enough available VRAM. GPU support is checked before creation." },
  { id: "microvm", title: "Create a MicroVM", group: "Create environments", steps: ["Select New environment → MicroVM.", "Choose the built-in Alpine image or supply a supported JSON boot manifest. Set resources and storage.", "Create it and use its node to start and open the MicroVM."], note: "MicroVMs use a separate kernel. Check image and networking requirements in the form before creating one." },
  { id: "vm", title: "Create a full VM", group: "Create environments", steps: ["Select New environment → VM.", "Choose an installer ISO or supported disk image, set its storage drive and resources, then create the VM.", "Start and open it. If you chose an ISO, finish operating-system installation in the VM window."], note: "Leave enough disk space for both the virtual disk and the operating system." },
  { id: "cloud", title: "Connect a cloud environment", group: "Create environments", steps: ["Select New environment → Cloud environment.", "Enter the existing server's SSH address, user and identity file or supported key material.", "Press Connect to verify access, then add the cloud node."], note: "This connects to an existing Linux server; it does not create or power on a cloud VM." },
  { id: "runpod", title: "Rent a GPU with Neocloud", group: "Create environments", steps: ["Select New environment → Neocloud.", "Paste your API key once, then choose a GPU pod, serverless endpoint, CPU pod or network volume.", "Pick a template and a GPU, review the hourly price and create it. The node opens with a terminal and files as soon as the pod is ready."], note: "Neocloud bills your account per second while a pod runs, and a stopped pod still pays for its volume. Stop or delete pods from their node." },
  { id: "shared", title: "Import a shared environment", group: "Create environments", steps: ["Ask the owner for the full share link, recipient username and password.", "Select New environment → Shared environment and enter those details.", "Connect to add the remote node. Later, press Reconnect to sign in with saved details. If a quick link or recipient password changes, use Connect to Shared Environment on that same node to update it."], note: "The workload stays on the owner's computer and your access follows the owner's permissions." },
  { id: "public", title: "Create a public access setup", group: "Connect and publish", steps: ["Open Domains above the environment list.", "Enter the app port, domain, local tunnel port and Cloudflare tunnel token. Route the domain to the shown local address in Cloudflare, then save.", "On a running environment, open the matching service port and choose the saved domain under Choose your public link."], note: "A quick link needs no account but changes when its tunnel restarts. Protect any public service that should be private." },
  { id: "share", title: "Share an environment", group: "Connect and publish", steps: ["Open the environment's Share control and choose who may connect.", "Set a recipient username, password and permission level, then enable the tunnel if needed.", "Copy that recipient's full share link and send the link and credentials to them through a trusted channel."], note: "Yougori must remain open while the share is active. The owner can revoke a recipient or disconnect remote users." },
  { id: "vault", title: "Use Personal Vault MCP", group: "Connect and publish", steps: ["Open Personal Vault MCP at the top. Create your vault if this is your first visit, then add one or more private items.", "For an agent on this computer, copy the local MCP URL. For ChatGPT, Claude or another online agent, connect a Cloudflare tunnel and copy its public MCP URL.", "Add that URL as a custom MCP server in the agent. Review connection and item-access requests in Yougori before approving them."], note: "Keep Yougori open for remote access. Share credentials only when you recognize the request and intend to disclose them." },
  { id: "model", title: "Run a Hugging Face model", group: "Use and manage", steps: ["Select Huggingface at the top of the main window.", "Enter a public text-generation model as hf.co/owner/model. Optionally select Create a local API and choose a port.", "Press Run model. The GPU node shows setup progress and logs. Open its terminal chat after the model is ready."], note: "Requires supported NVIDIA CUDA and enough VRAM. Model weights remain in a persistent volume." },
  { id: "list", title: "Use the List view", group: "Use and manage", steps: ["The workspace opens in the environment list. Use Environments above the terminal to return to it.", "Search with /, filter by status or type, group rows and click a column header to sort.", "Expand a row for its runtime, allocation, connections and ports, tick rows to start or stop several at once, or double-click a row to configure it."], note: "Switching views does not stop your environments." },
  { id: "cli", title: "Open the CLI", group: "Use and manage", steps: ["Choose CLI to the left of Projects in the bottom bar, or press Ctrl+`.", "A terminal opens in your Yougori workspace. Type yougori and press Enter to see its commands.", "Use the three-dot menu for Skills and Install tools. Switching views keeps the terminal session running."], note: "This CLI runs on your computer, not inside a container." },
  { id: "commands", title: "Use CLI commands", group: "Use and manage", steps: ["Type yougori or yougori help to see the complete command list.", "Start a workload with yougori run -d --name website -p 8080:80 nginx:alpine, then inspect it with yougori ps, yougori logs website and yougori inspect website.", "Use yougori stop website, yougori start website or yougori rm website to manage it. Use yougori up with a yougori.yaml project."], note: "Removing an environment deletes its local data. Use the command list to check syntax before a destructive action." },
  { id: "duplicate", title: "Duplicate an environment", group: "Use and manage", steps: ["On the list row, choose the Duplicate icon beside Settings.", "Choose Local or Cloud, then review the copy destination and options.", "Start the copy and follow its progress in the activity view."], note: "Cloud copies can create billable resources. Check what files and configuration will be transferred before starting." },
  { id: "delete", title: "Delete a node", group: "Use and manage", steps: ["Right-click the node and choose Delete node, or open its settings and choose Delete environment.", "Read the confirmation: it describes which writable data, snapshots and permissions will be removed.", "Confirm deletion. The node can disappear while cleanup continues, so you can keep using Yougori."], note: "Export a backup first if you may need the environment later. Removing a shared entry does not delete the owner's workload." },
  { id: "reclaim", title: "Reclaim space", group: "Use and manage", steps: ["Check free space on each drive in the bottom bar.", "Stop containers first when possible, then press Reclaim space beside Instructions.", "Wait for cleanup to finish and check the drive's free-space value again."], note: "Reclaiming compacts unused disk blocks; it keeps images, snapshots and exported backups." },
  { id: "theme", title: "Change the theme", group: "Use and manage", steps: ["Open the theme control beside Reclaim space in the bottom bar.", "Choose light, dark or a preset color palette.", "For a personal palette, enter four colors in Custom and save it."], note: "The selected appearance is saved for the main app and environment windows." },
] as const

export const instructionGuideIds = new Set(instructionGuides.map(guide => guide.id))
