import { test, expect } from "@playwright/test"

test.beforeEach(async ({ page }) => { await page.addInitScript(() => localStorage.setItem("yougori.instructions.seen.v1", "1")) })

test("host CLI restores the startup shell, preserves it across views, and closes only the selected tab", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", error => errors.push(error.message))
  await page.addInitScript(() => localStorage.setItem("yougori.workspace-view", "nodes"))
  await page.goto("/")
  await expect(page.getByRole("table", { name: "Environments", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Nodes", exact: true })).toHaveCount(0)
  await expect(page.locator(".react-flow")).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem("yougori.workspace-view"))).toBe("list")
  const footer = page.locator(".workspace-footer-actions")
  await expect(footer.getByRole("button", { name: /^(CLI|Projects)$/ })).toHaveText(["CLI", "Projects"])
  await expect(page.locator(".workspace-view-toolbar").getByRole("button", { name: "CLI", exact: true })).toHaveCount(0)
  await footer.getByRole("button", { name: "CLI", exact: true }).click()
  const panel = page.getByRole("region", { name: "Yougori CLI", exact: true })
  await expect(panel.getByRole("tab", { name: "Terminal 1", exact: true })).toBeVisible()
  await expect(panel.locator(".xterm-screen")).toBeVisible()
  const sessions = () => page.evaluate(async () => { const path = "/src/api/host-terminal-api.ts"; return (await (await import(path)).hostTerminalApi.info()).sessions })
  await expect.poll(async () => (await sessions()).length).toBe(1)
  const initial = (await sessions())[0]!
  expect(initial.cwd).toBe("C:\\Users\\Test\\Yougori\\Workspace")
  const screen = panel.locator(".host-terminal-xterm")
  await screen.click()
  await page.keyboard.type("echo HOST_INPUT")
  await page.keyboard.press("Enter")
  await expect.poll(() => page.evaluate(async () => { const path = "/src/api/host-terminal-api.ts"; const api = (await import(path)).hostTerminalApi; const info = await api.info(); return atob((await api.terminal({ action: "read", sessionId: info.sessions[0].sessionId })).data) })).toContain("echo HOST_INPUT")
  await page.keyboard.press("Control+Backquote")
  await expect(panel).toBeHidden()
  await page.keyboard.press("Control+Backquote")
  await expect(panel).toBeVisible()
  expect((await sessions())[0]!.sessionId).toBe(initial.sessionId)
  await panel.getByRole("button", { name: "CLI actions" }).click()
  await page.getByRole("menuitem", { name: "Open folder in new terminal" }).click()
  await expect(panel.getByRole("tab", { name: "Terminal 2", exact: true })).toBeVisible()
  await expect.poll(async () => (await sessions()).length).toBe(2)
  expect((await sessions())[1]!.cwd).toBe("C:\\Projects\\website")
  await panel.getByRole("button", { name: "New terminal tab" }).click()
  await expect.poll(async () => (await sessions()).length).toBe(3)
  expect((await sessions())[2]!.cwd).toBe("C:\\Projects\\website")
  await panel.getByRole("button", { name: "New terminal tab" }).click()
  await expect.poll(async () => (await sessions()).length).toBe(4)
  await expect(panel.getByRole("button", { name: "New terminal tab" })).toBeDisabled()
  await panel.getByRole("button", { name: "Close Terminal 2", exact: true }).click()
  const confirm = page.getByRole("dialog", { name: "Close terminal?" })
  await confirm.getByRole("button", { name: "Cancel" }).click()
  expect(await sessions()).toHaveLength(4)
  await panel.getByRole("button", { name: "Close Terminal 2", exact: true }).click()
  await confirm.getByRole("button", { name: "Close terminal", exact: true }).click()
  await expect.poll(async () => (await sessions()).length).toBe(3)
  expect((await sessions())[0]!.sessionId).toBe(initial.sessionId)
  await expect(panel.getByRole("tab", { name: "Terminal 2", exact: true })).toHaveCount(0)
  await expect(panel.getByRole("button", { name: "New terminal tab" })).toBeEnabled()
  expect(errors).toEqual([])
})

test("Edit the App opens a separate terminal in the source checkout with editing guidance", async ({ page }) => {
  await page.goto("/")
  const views = page.locator(".workspace-footer-actions")
  // Navigation completes at the lightweight loading document. Assert the
  // workspace is ready before checking controls that only exist inside it.
  await expect(views).toBeVisible({ timeout: 60000 })
  await expect(page.locator(".workspace-view-toolbar").getByRole("button", { name: "Edit the App" })).toHaveCount(0)
  const editButton = page.getByRole("button", { name: "Edit the App" })
  await expect(editButton).toBeVisible()
  await expect(editButton).toHaveAttribute("aria-pressed", "false")
  await editButton.click()
  await expect(editButton).toHaveAttribute("aria-pressed", "true")
  const editor = page.getByRole("region", { name: "Edit the App" })
  await expect(editor).toBeVisible()
  await expect(editor.getByText("C:\\Projects\\yougori")).toBeVisible()
  await expect(editor.getByRole("tab", { name: "Terminal 1" })).toBeVisible()
  await editor.getByRole("button", { name: "CLI actions" }).click()
  await page.getByRole("menuitem", { name: "Skills" }).click()
  await expect(page.getByRole("dialog", { name: "Skills" }).getByText("Edit Yougori")).toBeVisible()
  await page.getByRole("dialog", { name: "Skills" }).getByRole("button", { name: "Copy both guides" }).click()
  await page.keyboard.press("Escape")
  await views.getByRole("button", { name: "CLI", exact: true }).click()
  await expect(page.getByRole("region", { name: "Yougori CLI" }).getByRole("tab", { name: "Terminal 1" })).toBeVisible()
  await editButton.click()
  await expect(editor.getByRole("tab", { name: "Terminal 1" })).toBeVisible()
  const sessions = await page.evaluate(async () => { const path = "/src/api/host-terminal-api.ts"; return (await (await import(path)).hostTerminalApi.info()).sessions })
  expect(sessions.some(session => session.sessionId.startsWith("host-edit-") && session.cwd === "C:\\Projects\\yougori")).toBe(true)
  expect(sessions.some(session => !session.sessionId.startsWith("host-edit-") && session.cwd === "C:\\Users\\Test\\Yougori\\Workspace")).toBe(true)
})
