import type { InstructionsTour, TourStep } from "@/lib/instructions-tour"
import { tourPreviewId } from "@/lib/tour-preview"
import { defaultOciImage } from "@/data/oci-images"

export interface TourExplanation { title: string; body: string; hint?: string; target: string; extra?: string[]; interactive?: boolean; next?: string }
export function tourExplanation(step: TourStep, tour: InstructionsTour): TourExplanation {
  const node = `[data-environment-id="${CSS.escape(tour.environmentId ?? tourPreviewId(tour))}"]`
  const graph = '[data-environment-canvas]'
  const serviceDialog = `[data-service-options="${tour.environmentId ?? ""}"][data-service-port="3000"]`
  const content: Record<TourStep, TourExplanation> = {
    welcome: { title: "Let's look around", body: "We'll use a temporary preview row to explore the app. Then you'll create one default container, connect Internet access, try tools and windows, and share your first website. Yougori builds the website for you automatically.", hint: "Skip to hands-on jumps to the practical walkthrough and removes the preview. During hands-on, Skip ends the guide and keeps any real work you have started.", target: '[data-tour="instructions"]' },
    stats: { title: "Your computer, at a glance", body: "These charts show your PC's CPU, GPU and memory usage. The bottom bar shows free space on each mounted drive. Choose a storage drive when creating an environment.", hint: "A virtual disk's capacity is its limit, not necessarily space already used.", target: '[aria-label="Host resources and storage"]' },
    graph: { title: "Your environments", body: "Every environment appears as a row here. Search, filter and sort the list, or expand a row for its details. This Tutorial preview lets you see the controls before creating anything.", target: graph },
    "node-controls": { title: "Start, open and stop", body: "A row shows its status and usage. The main button changes from Start to Stop while running, or Resume while paused. The terminal icon opens a running environment. Stop ends its running programs. Closing a window does not stop the environment.", hint: "This preview is for looking around. You'll use these controls on your own container shortly.", target: node },
    configuration: { title: "Settings and recovery", body: "Double-click a row or select its name to open its settings. Change resource limits, save changes, manage connections, take snapshots or back up a stopped environment.", hint: "Factory reset erases environment data. Delete removes the environment. Neither is needed for this tutorial.", target: `${node} [data-tour="node-configure"]` },
    connections: { title: "Connect environments privately", body: "Choose + Connect in an environment's Connections column to connect it to another environment. Choose one-way or both ways, allowed TCP ports, and file/data permissions.", hint: "File access shares a designated connection folder, not the other environment's entire disk. Skills explains the saved permissions and offline peers.", target: `${node} [data-tour="row-connect"]` },
    "my-pc": { title: "Share selected PC folders", body: "Turn on My PC in an environment's Access column to choose folders it may access. Nothing is shared until you choose folders. Read-only is the safer starting point.", hint: "Writable shares can change original files on your PC. They are not copies inside the environment.", target: `${node} [data-tour="row-pc"]` },
    "internet-overview": { title: "Wi-Fi or cable: Internet access", body: "This gives an environment Internet access through your PC's existing connection. It works whether your PC uses Wi-Fi or Ethernet; there is no separate Wi-Fi login inside the container.", hint: "Use the Internet switch in the row's Access column to allow or block access.", target: `${node} [data-tour="row-internet"]` },
    "service-ports": { title: "Add a service port", body: "Click Ports & access on a container, MicroVM or VM row. In Add a service port, enter the Guest TCP port your app uses, such as 3000, or choose a common port. Click Add port to show it in the row and open its connection options.", hint: "Use 1–65535; 7443 is reserved. Adding a port does not start your app or publish it. Run the app, then choose Local network or Public access in its settings separately.", target: `${node} [data-tour="node-port"]` },
    "local-network": { title: "Share a running service locally", body: "A website or database needs a listening port. Its port appears in the row, or you can add one with Ports & access. Open its settings and choose Local network to make the service reachable from your PC and permitted private-network devices.", hint: "This is separate from a private node-to-node link. Cloud environments cannot use this destination.", target: `${node} [data-tour="node-port"]` },
    "public-access": { title: "Publish a service on the web", body: "Open Ports & access and choose Public access / Cloudflare Tunnel for a local environment's service port for a public link. Account authentication is optional. Your app still needs its own access protection.", hint: "Later, you can publish our fixed Hello World page. Nothing is published until you press Publish service. Anyone with its link can visit it.", target: `${node} [data-tour="node-port"]` },
    backups: { title: "Bring back a local backup", body: "New environment → Load local backup restores a saved Yougori backup as a new environment. To make one, open the environment's settings and choose Back up to this PC while it is stopped.", hint: "Keep the whole backup folder together. Shared PC folders and live tunnel connections are not part of that backup.", target: '[data-tour="new-environment"]' },
    "host-terminal": { title: "Yougori CLI", body: "Open CLI to the left of Projects in the bottom bar to use your computer’s shell in your workspace folder. Skills and tool installers are in the three-dot menu.", hint: "Switch views without closing your terminal session. Ctrl+` toggles the CLI.", target: '#host-terminal-toggle' },
    cloud: { title: "Connect an existing cloud server", body: "Choose New environment → Cloud environment to add an existing Linux server from AWS, Google Cloud, Azure or another provider. Supply its SSH address, user and identity file, then click Connect to test the connection.", hint: "Requires SSH and Python 3. Connect/Disconnect does not power the server on or off. Private links are allowed; Local network and Public access are not.", target: '[data-tour="new-environment"]' },
    theme: { title: "Choose your appearance", body: "Pick light, dark, or one of the color palettes. You can also enter four colors for a custom theme. Your choice is saved for the app and its environment windows.", target: '.dashboard-theme' },
    settings: { title: "Set up Yougori for your computer", body: "Settings is at the top of the main window. There you can launch Yougori when you sign in, keep the computer awake while environments run, and choose which environments start automatically.", hint: "The default storage folder is also shown there. Each new environment can use a different drive; changing the shared runtime folder requires exporting and removing existing environments first.", target: '[data-tour="settings"]' },
    "environment-types": { title: "Choose what to run", body: "New environment offers lightweight containers, NVIDIA CUDA GPU containers, MicroVMs and full VMs. GPU support depends on compatible hardware and runtime setup; it is not promised on every computer.", hint: "We'll start with an ordinary Linux container—no OS installer is needed.", target: '[data-tour="new-environment"]' },
    "windows-overview": { title: "Inside an environment window", body: "You'll find terminal tabs, Install tools, New window and window/environment switchers. Connected environments also show Skills. Terminal links can appear as QR cards that you can close.", hint: "That's the overview. Next begins the first-container walkthrough using the actual controls.", target: graph, next: "Next" },
    "create-open": { title: "Create your first container", body: "Click New environment. The guide will stay with you inside the form. No environment is created until you press the form's Create environment button.", target: '[data-tour="new-environment"]', interactive: true },
    "create-type": { title: "Use the default container", body: "Container is selected for this guide. We'll use this one Linux workspace for the tools, windows and website, so you only build one website.", target: '[aria-label="Isolation options"]', interactive: true, hint: "Other environment types become available after you finish or skip the guide. Press Next to name your container." },
    "create-name": { title: "Give it a name", body: "Enter a name you will recognize, such as First container. Use at least two characters and a name that is not already in your list.", target: '[data-tour="create-name"]', interactive: true },
    "create-image": { title: "Your default Linux image", body: `${defaultOciImage.label} is already selected. The guide keeps this image and its startup command ready for your first website. No image search or extra container is needed.`, hint: "After the guide, you can choose other images for new projects.", target: '[data-tour="create-image"]' },
    "create-resources": { title: "Allocate CPU, memory and storage", body: "Set one fixed CPU value and one fixed memory value using the sliders or number fields. For coding tools, allow around 2 GB of memory if your PC has room. Keep some capacity for your PC.", hint: "Storage is an independent writable limit for this container. You can increase it later in Configuration.", target: '[aria-label="Resource allocation"]', interactive: true },
    "create-submit": { title: "Create the container", body: "Check your choices, then click Create environment below. The form closes and the row shows progress while its image and storage are prepared.", hint: "The guide continues when preparation finishes. Errors appear on the row or in a notification. Skip never cancels an operation already started.", target: '[data-tour="create-submit"]', extra: ['[data-create-environment] [role="alert"]'], interactive: true },
    created: { title: "This is your new container", body: "Your container is created and has its own row. Its files survive normal stops and starts. We'll check Internet access before opening it.", target: node },
    "internet-connect": { title: "Check Internet access", body: "Internet starts on by default. Use the switch in your new environment's Access column to allow or block it, even while the container is running.", hint: "This uses your PC's Wi-Fi or wired connection. It does not share PC files or publish any ports. Next unlocks when access is connected.", target: `${node} [data-tour="row-internet"]`, extra: [`${node} [data-tour="row-internet"]`], interactive: true },
    start: { title: "Start and open it", body: "Click Start on your new row. If it is already running, click the terminal icon to open it. Wait for preparation to finish; the guide continues in the container's window.", hint: "Start failures remain visible in the app. Correct the error and retry; don't delete or reset the environment just to continue the guide.", target: `${node} [data-tour="node-launch"]:not([data-running="true"]), ${node} [data-tour="node-open"]`, extra: ['[role="alert"]'], interactive: true },
    "first-window": { title: "Opening your container…", body: "Keep Yougori open while it starts. The instructions will move into the new container window automatically.", hint: "If you cannot see it, check your taskbar. Skip ends the guide only; it does not stop the container.", target: node },
    terminal: { title: "This terminal is inside the container", body: "Commands here run in the container, not in your PC's PowerShell. Wait until its prompt is ready. Paste works with Ctrl+V; Ctrl+C interrupts a command when no text is selected.", hint: "Later, Yougori will build your demo website automatically. You won't need to copy or paste a website command.", target: '[data-tour="guest-terminal"]' },
    tabs: { title: "Separate terminals, same container", body: "Each tab is a separate terminal session. Use + for another tab; files remain shared because the tabs belong to the same container. Closing a tab ends that terminal session.", target: '[data-workspace-tabs]' },
    install: { title: "Install Codex", body: "Open Install tools, then choose Codex. Its installer starts in a fresh terminal tab so it does not overwrite what you were typing. Internet access must stay connected.", hint: "Click the real Codex menu item. The guide advances only after the installer command is sent. If it fails, check the terminal error and retry from Install tools.", target: '[data-tour="install-tools"]', extra: ['[data-tour="installer-menu"]'], interactive: true },
    "install-running": { title: "Watch the installation", body: "The Codex installer has been started—not yet verified as finished. Read this tab's output and wait for its completion message. If it reports an error, fix that error before continuing.", hint: "Next does not mean installation succeeded. Keep this tab open until the installer finishes.", target: '[data-tour="guest-terminal"]', interactive: true },
    "new-terminal": { title: "Open a fresh terminal tab", body: "When installation has finished, click + beside the tabs. A fresh terminal picks up the newly installed tool's environment.", target: '[data-tour="new-terminal"]', interactive: true },
    "run-codex": { title: "Use Codex in the container", body: "Type codex and press Enter in this terminal. Follow the tool's own account and setup prompts. If it says command not found, return to the installer output and check whether installation finished.", hint: "The guide does not sign in, enter credentials, or submit prompts. Press Next when you're ready to learn about windows.", target: '[data-tour="guest-terminal"]', interactive: true },
    "new-window": { title: "Open another window", body: "Click New window. It opens this same running container in a separate window with its own terminal tabs. It does not create or copy another container.", hint: "Your files are shared between these windows. The guide will continue in the new one.", target: '[data-tour="new-window"]', interactive: true },
    "second-window": { title: "Opening another window…", body: "The next tip will appear in the newly opened window. Both windows use the same container and files.", target: '[data-tour="new-window"]' },
    "window-switcher": { title: "Move between open windows", body: "Windows lists the environment windows that are already open. Select one to bring it to the front. Closing a window is different from stopping the container.", target: '[data-tour="window-switcher"]' },
    "environment-switcher": { title: "One container for this guide", body: "The name menu can switch between environments. During the guide, we stay in your default container. Next, Yougori will create and start one website here automatically.", hint: "Your other environments are left alone. You can switch to them after the guide.", target: '[data-tour="environment-switcher"]' },
    "demo-start": { title: "Building your first website", body: "Yougori is putting a complete Hello World website into your tutorial container, setting up what it needs, and starting it on port 3000. No copying or pasting. We'll continue as soon as it's ready.", hint: "Keep Internet access connected for setup. Only the demo page is served; no folders or PC files. The website stays private until you choose Publish service.", target: '[data-tour="guest-terminal"]' },
    "demo-return": { title: "Your website is ready", body: "Your Hello World website has been created, started and checked in this container. Continue below, then switch to the main Yougori window to add its port and get a shareable link.", hint: "The website runs in the background, so you can close this terminal. Stopping the container stops the website.", target: '[data-tour="guest-terminal"]', next: "Continue on main window" },
    "demo-port-open": { title: "Add the website's port", body: "On your tutorial container, click Ports & access. We'll add 3000—the same port used by the Hello World website. Even if it was detected automatically, adding the same port does not create a duplicate.", target: `${node} [data-tour="node-port"]`, interactive: true },
    "demo-port-add": { title: "Enter port 3000", body: "Enter 3000 in Guest TCP port, or click the 3000 shortcut, then click Add port. The connection options will open next. This step alone does not publish your website.", target: `[data-add-service-port="${tour.environmentId ?? ""}"]`, interactive: true },
    "demo-publish": { title: "Get a free public link", body: "Choose Public access / Cloudflare Tunnel, keep Quick link — no account selected, then press Publish service. This makes the Hello World page accessible on the public Internet.", hint: "No login, payment or domain purchase is needed. Cloudflare assigns a temporary random trycloudflare.com address—not a permanent domain you own. Wait for the link; the first helper download may take a while. Skip does not cancel publishing already started.", target: serviceDialog, interactive: true },
    "demo-link": { title: "Open your public website", body: "Your public link is ready. Click the HTTPS address in these connection options to open it in your browser. You can also copy it and visit it from a phone or another computer.", hint: "A connected tunnel is not proof the page loaded. If you see an error, keep the website terminal running and wait briefly, then retry the link. Disconnect Cloudflare here to take the site offline.", target: serviceDialog, interactive: true },
    "demo-visit": { title: "Does it say Hello World?", body: "Check the browser tab you opened. If you see Hello World, your container website is now reachable through its public link. Return here and press Next when you have confirmed it.", hint: "To take it offline, use Disconnect cloudflare here. The link also stops when Yougori or the container stops, and a new tunnel gets a new address. Closing the browser is not the same as disconnecting.", target: serviceDialog, interactive: true },
    done: { title: "You're ready to explore", body: "You've created a container, connected Internet access, learned about tools and windows, and published your first Hello World website.", hint: "Finish keeps your environment and any active public link. Disconnect Cloudflare in the port's options when you no longer want it public. Use Instructions to replay the guide.", target: node, extra: [serviceDialog], interactive: true, next: "Finish" },
  }
  return content[step]
}
