import { CloudDeploymentWarning, cloudRiskAcknowledgement } from "@/components/cloud-deployment-warning"
import { useState } from "react"
import { CloudUploadIcon } from "lucide-react"
import { cloudApi,cloudOptionKinds,type CloudDeployRequest,type CloudOptions } from "@/api/cloud-api"
import { usePlatform } from "@/context/platform-context"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Dialog,DialogHeader,DialogTitle,DialogDescription,DialogPanel,DialogFooter,DialogPopup,DialogTrigger } from "@/components/ui/dialog"
import { Checkbox } from "@/components/ui/checkbox"
const initial:CloudDeployRequest={provider:"aws",account:"",region:"",name:"",image:"",machineType:"",subnet:"",resourceGroup:"",securityGroup:"",keyPair:"",sshPublicKey:"",imageProject:"",containerImage:"",username:"ubuntu"}
export function CloudDeploymentDialog({ triggerClassName, triggerDisabled, embedded = false, onClose, onBusyChange }: { embedded?: boolean; onClose?(): void; onBusyChange?(busy: boolean): void; triggerClassName?: string; triggerDisabled?: boolean }){
  const {deployCloudEnvironment}=usePlatform()
  const [open,setOpen]=useState(false),[request,setRequest]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[authenticated,setAuthenticated]=useState(false),[reviewed,setReviewed]=useState(false),[sso,setSso]=useState<Record<string,string>>({})
  const [choices,setChoices]=useState<Partial<Record<keyof CloudDeployRequest,CloudOptions>>>({}),[loading,setLoading]=useState(false),[lookupError,setLookupError]=useState("")
  const edit=(key:keyof CloudDeployRequest,value:string)=>{setRequest(r=>({...r,[key]:value,...(key==="image"&&choices.image?.imageProject&&!r.imageProject&&choices.image.items.some(i=>i.id===value)?{imageProject:choices.image.imageProject}:{})}));setReviewed(false);if(key==="provider"||key==="account"){setAuthenticated(false);setChoices({})}}
  // Read-only provider lookups fill suggestion lists; every field still accepts typed values.
  const lookUp=async()=>{if(loading)return;setLoading(true);setLookupError("");const failures:string[]=[];const found:typeof choices={}
    await Promise.all(cloudOptionKinds(request.provider,request.region).map(async kind=>{try{const result=await cloudApi.options(request.provider,request.account,request.region,kind);found[result.field]=result}catch(reason){failures.push(`${kind}: ${String(reason)}`)}}))
    setChoices(c=>({...c,...found}));setLookupError(failures.join("\n"));setLoading(false)}
  const perform=async(action:()=>Promise<unknown>)=>{if(busy)return;onBusyChange?.(true);setBusy(true);setError("");try{await action()}catch(reason){setError(String(reason))}finally{setBusy(false);onBusyChange?.(false)}}
  const fields:[keyof CloudDeployRequest,string,string][]=[["name","Environment name","website"],["region",request.provider==="google"?"Zone":"Region",request.provider==="aws"?"eu-west-1":request.provider==="azure"?"westeurope":"europe-west1-b"],["image",request.provider==="aws"?"AMI ID":request.provider==="azure"?"VM image URN or ID":"VM image name","Provider image ID"],["machineType","Machine type / size",request.provider==="aws"?"t3.small":request.provider==="azure"?"Standard_B2s":"e2-small"],["subnet","Existing subnet ID / name","Your configured subnet"],["username","SSH username","ubuntu"]]
  if(request.provider==="aws")fields.push(["securityGroup","Existing security group ID","sg-…"],["keyPair","Existing EC2 SSH key pair name","yougori"])
  if(request.provider==="azure")fields.push(["resourceGroup","Existing resource group","my-project"],["securityGroup","Existing network security group","Your NSG name or ID"])
  if(request.provider==="google")fields.push(["imageProject","Image project","ubuntu-os-cloud"])
  const content = <>{embedded ? <p className="px-6 pt-4 text-sm text-muted-foreground">Create a VM in your cloud account. Provider credentials stay in the official CLI’s credential store.</p> : <DialogHeader><DialogTitle>Deploy a cloud environment</DialogTitle><DialogDescription>Create a VM directly in your account. Requires the official AWS CLI, Azure CLI, or Google Cloud CLI on this computer. Provider credentials stay in that CLI’s credential store.</DialogDescription></DialogHeader>}<DialogPanel className="space-y-5"><fieldset disabled={busy} className="space-y-4"><div role="group" aria-label="Deployment provider" className="flex gap-2">{([['aws','AWS'],['azure','Azure'],['google','Google Cloud']]as const).map(([key,label])=><Button key={key} variant={request.provider===key?"default":"outline"} size="sm" onClick={()=>edit("provider",key)}>{label}</Button>)}</div><label className="block space-y-2 text-sm">{request.provider==="aws"?"AWS SSO profile":request.provider==="azure"?"Azure subscription ID":"Google Cloud project ID"}<Input value={request.account} onChange={e=>edit("account",e.target.value)} autoComplete="off"/></label>
    {request.provider==="aws"?<details className="rounded border p-3 text-xs"><summary>Configure an AWS SSO profile (optional)</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['sso_start_url','SSO start URL'],['sso_region','SSO region'],['sso_account_id','AWS account ID'],['sso_role_name','Role name']]as const).map(([key,label])=><label key={key} className="space-y-1">{label}<Input value={sso[key]??""} onChange={e=>{setSso(v=>({...v,[key]:e.target.value}));setAuthenticated(false)}}/></label>)}</div></details>:null}
    <Button disabled={busy||!request.account} variant="outline" onClick={()=>void perform(async()=>{await cloudApi.authenticate(request.provider,request.account,Object.values(sso).some(Boolean)&&request.provider==="aws"?sso:undefined);setAuthenticated(true)})}>{authenticated?"Authenticated — sign in again":"Authenticate in browser"}</Button>
    <div className="flex flex-wrap items-center gap-3"><Button disabled={busy||loading||!request.account} loading={loading} variant="outline" size="sm" onClick={()=>void lookUp()}>{Object.keys(choices).length?"Refresh choices":"Look up choices"}</Button><span className="text-xs text-muted-foreground">Lists regions, images, sizes and networks from your account. Nothing is created. Pick a region, then look up again for sizes.</span></div>{lookupError?<p role="alert" className="whitespace-pre-wrap text-xs text-destructive-foreground">{lookupError}</p>:null}
    <div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label,placeholder])=><label key={key} className="space-y-2 text-sm">{label}<Input value={request[key]} placeholder={placeholder} onChange={e=>edit(key,e.target.value)} autoComplete="off" spellCheck={false} list={choices[key]?.items.length?`cloud-choices-${key}`:undefined}/>{choices[key]?.items.length?<datalist id={`cloud-choices-${key}`}>{choices[key].items.map(item=><option key={item.id} value={item.id} label={[item.name!==item.id?item.name:"",item.detail].filter(Boolean).join(" · ")}/>)}</datalist>:null}</label>)}</div>{request.provider!=="aws"?<label className="block space-y-2 text-sm">SSH public key<textarea className="min-h-20 w-full rounded border bg-background p-2 font-mono text-xs" value={request.sshPublicKey} onChange={e=>edit("sshPublicKey",e.target.value)} placeholder="ssh-ed25519 AAAA…"/>{choices.sshPublicKey?.items.length?<span className="flex flex-wrap gap-2">{choices.sshPublicKey.items.map(key=><Button key={key.id} type="button" variant="outline" size="xs" onClick={()=>edit("sshPublicKey",key.id)}>Use {key.name}</Button>)}</span>:null}</label>:null}
    <label className="block space-y-2 text-sm">OCI workload image (optional, Ubuntu VM images only)<Input value={request.containerImage} onChange={e=>edit("containerImage",e.target.value)} placeholder="docker.io/library/nginx:alpine"/></label><p className="text-xs text-muted-foreground">Optional workload setup installs Podman and Python 3, runs the image through systemd, and maps VM port 8080 to container port 80. Image startup may take several minutes after VM creation. Azure VMs use a private IP in the selected subnet; connect through your VPN or private network. Existing firewall rules control access; Yougori does not open ingress rules.</p>
    <div className="rounded-lg border p-4 text-sm"><p className="font-medium">Deployment review</p><p>{request.provider} · {request.account||"No account"} · {request.region||"No region"}</p><p>{request.machineType||"No machine size"} · {request.image||"No image"}</p><p className="mt-2 text-xs text-muted-foreground">This creates billable compute, disk and network resources. Stopping compute can leave storage and other resources billable. Review your provider’s pricing and the existing subnet/security rules.</p></div><CloudDeploymentWarning /><label className="flex items-start gap-2 text-sm"><Checkbox checked={reviewed} onCheckedChange={value=>setReviewed(value===true)}/>{cloudRiskAcknowledgement}</label><Button disabled={busy||!authenticated||!reviewed} loading={busy} onClick={()=>void perform(async()=>{await deployCloudEnvironment(request, reviewed);setOpen(false);onClose?.();setReviewed(false)})}>Create cloud environment</Button></fieldset>{busy?<p role="status" className="text-sm text-muted-foreground">Waiting for authentication or provisioning. A deployment can take several minutes.</p>:null}{error?<p role="alert" className="whitespace-pre-wrap text-sm text-destructive-foreground">{error}</p>:null}</DialogPanel>{embedded ? <DialogFooter><Button type="button" variant="ghost" disabled={busy} onClick={onClose}>Cancel</Button></DialogFooter> : null}</>
  if (embedded) return content
  return <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogTrigger render={<Button className={triggerClassName} disabled={triggerDisabled} type="button" size="sm" variant="outline"/>}><CloudUploadIcon aria-hidden="true" /><span>Deploy to cloud</span></DialogTrigger><DialogPopup className="w-[min(70rem,calc(100vw-2rem))] max-w-none" closeProps={{disabled:busy}}>{content}</DialogPopup></Dialog>
}
